{
 "title": "DarkRift",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Connected",
   "type": "stat",
   "description": "The total number of clients currently connected to DarkRift servers.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(darkrift_client_manager_clients_connected)"
    }
   ]
  },
  {
   "title": "Clients Connected Per Server",
   "type": "stat",
   "description": "The number of clients currently connected to each DarkRift server.",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "darkrift_client_manager_clients_connected",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "options": {
    "content": "These graphs show the current rates of messages and data going through your DarkRift servers.\n\nThe data rate graphs on the right are configured to use a Bichannel Listener and expect it to be called `DefaultNetworkListener`. If you're using a different network listener you'll need to change the graphs appropriately!\n\nNote, metrics for these graphs are only recorded if `enablePerMessageMetrics` is `true` in your configuration."
   }
  },
  {
   "title": "UDP Bytes Sent",
   "type": "graph",
   "description": "The number of bytes sent to the DarkRift server via UDP.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_default_network_listener_bytes_sent{protocol=\"udp\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP Bytes Received",
   "type": "graph",
   "description": "The number of bytes received by the DarkRift server via UDP.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_default_network_listener_bytes_received{protocol=\"udp\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "description": "The number of messages sent from the DarkRift server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_client_messages_sent[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "description": "The number of messages received by the DarkRift server.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_client_messages_received[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Bytes Sent",
   "type": "graph",
   "description": "The number of bytes sent to the DarkRift server via TCP.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_default_network_listener_bytes_sent{protocol=\"tcp\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP Bytes Received",
   "type": "graph",
   "description": "The number of bytes received by the DarkRift server via TCP.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_default_network_listener_bytes_received{protocol=\"tcp\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total UDP Bytes Sent",
   "type": "graph",
   "description": "The number of bytes sent to the DarkRift server via UDP.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "darkrift_default_network_listener_bytes_sent{protocol=\"udp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total UDP Bytes Received",
   "type": "graph",
   "description": "The number of bytes received by the DarkRift server via UDP.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "darkrift_default_network_listener_bytes_received{protocol=\"udp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Messages Sent",
   "type": "graph",
   "description": "The number of messages sent from the DarkRift server.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    { "expr": "darkrift_client_messages_sent", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "graph",
   "description": "The number of messages received by the DarkRift server.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Message Rate" }
   ],
   "targets": [
    {
     "expr": "darkrift_client_messages_received",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total TCP Bytes Sent",
   "type": "graph",
   "description": "The number of bytes sent to the DarkRift server via TCP.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "darkrift_default_network_listener_bytes_sent{protocol=\"tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total TCP Bytes Received",
   "type": "graph",
   "description": "The number of bytes received by the DarkRift server via TCP.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "decbytes", "label": "Data Rate" }
   ],
   "targets": [
    {
     "expr": "darkrift_default_network_listener_bytes_received{protocol=\"tcp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 24 },
   "options": {
    "content": "You can use these graphs to gauge performance of your business logic in the server. The faster you can make your event handlers, the more messages and clients a DarkRift server will be able to handle.\n\nEvent failures indicate an issue with your business logic that you should investigate. The logs for that server will contain the exception that occured and may help you diagnose the problem. It can be a good idea to set and alert on these graphs!\n\nNote, timings for the Message Received event are only recorded if `enablePerMessageMetrics` is `true` in your configuration."
   }
  },
  {
   "title": "Average Client Connected Event Execution Time",
   "type": "graph",
   "description": "The average time it took to execute the Client Connected event on a 1 minute rolling averge.",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_client_manager_client_connected_event_time_sum[1m]) / rate(darkrift_client_manager_client_connected_event_time_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Message Recevied Event Execution Time",
   "type": "graph",
   "description": "The average time it took to execute the Message Received event on a 1 minute rolling averge.",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_client_message_received_event_time_sum[1m]) / rate(darkrift_client_message_received_event_time_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Client Disconnected Event Execution Time",
   "type": "graph",
   "description": "The average time it took to execute the Client Disconnected event on a 1 minute rolling averge.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(darkrift_client_manager_client_connected_event_time_sum[1m]) / rate(darkrift_client_manager_client_connected_event_time_count[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Connected Event Failures",
   "type": "graph",
   "description": "The number of failures executing the Client Connected event",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "darkrift_client_manager_client_connected_event_failures",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message Received Event Failures",
   "type": "graph",
   "description": "The number of failures executing the Message Received event",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "darkrift_client_message_received_event_failures",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Disconnected Event Failures",
   "type": "graph",
   "description": "The number of failures executing the Client Disconnected event",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "darkrift_client_manager_client_disconnected_event_failures",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Server Tuning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "options": {
    "content": "These graphs and counters are designed to help you identify some more complex and subtler issues with your DarkRift servers.\r\n\r\nIn general, if something's not green then there's an opportunity for improvement but they often require deep knowledge of DarkRift to sort!"
   }
  },
  {
   "title": "Object Finalizations",
   "type": "stat",
   "description": "The number of finalizations of recyclable objects in the time period. This number being non-zero is a sign that you are not recycling objects properly in your logic.\n\nWarnings will show in the logs of a server suffering from object recycling issues.",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "darkrift_object_cache_monitor_finalizations",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}